export const rawData = [
  {
    "patient_id": "CES001",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 1.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": NaN,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 1,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES001",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": NaN,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 1,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES002",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "10–14 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 5.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": NaN,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 1,
    "D_FAM_NB": 1,
    "D_CROYANCES": 1,
    "D_MED_TRAD": 1
  },
  {
    "patient_id": "CES002",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "10–14 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": NaN,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 1,
    "D_FAM_NB": 1,
    "D_CROYANCES": 1,
    "D_MED_TRAD": 1
  },
  {
    "patient_id": "CES003",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "10–14 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 2.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": NaN,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 1,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES003",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "10–14 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": NaN,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 1,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES004",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 2.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": NaN,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 1,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 1,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES004",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": NaN,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 1,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 1,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES005",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 0.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": NaN,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 1,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES005",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": NaN,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 1,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES006",
    "PERIODE": 1,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "10–14 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 4.0,
    "NB_HOSPIT": 1.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES006",
    "PERIODE": 2,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "10–14 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES007",
    "PERIODE": 1,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 0.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES007",
    "PERIODE": 2,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES008",
    "PERIODE": 1,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 0.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES008",
    "PERIODE": 2,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES009",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 0.0,
    "NB_HOSPIT": 1.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 1,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES009",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 1,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES010",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 1.0,
    "NB_HOSPIT": 1.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES010",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES011",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 1.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 1,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES011",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 1,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES012",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": NaN,
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 3.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 1,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 1,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES012",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": NaN,
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 1,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 1,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES013",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 1.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 1,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 1,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES013",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 1,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 1,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES014",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 3.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 1,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES014",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 0.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 1,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES015",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 0,
    "RDV_HONORE": NaN,
    "NB_CVO": 1.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES015",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 0,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES016",
    "PERIODE": 1,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 1.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 1,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES016",
    "PERIODE": 2,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 1,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES017",
    "PERIODE": 1,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": NaN,
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 1.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 1,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES017",
    "PERIODE": 2,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": NaN,
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 1,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES018",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 0.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES018",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES019",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 1.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 1,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES019",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 1,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES020",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": NaN,
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 3.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 1,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES020",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": NaN,
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 1,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES021",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "10–14 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 1.0,
    "NB_HOSPIT": 2.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES021",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "10–14 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES022",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 2.0,
    "NB_HOSPIT": 1.0,
    "NB_TRANSFUS": 1.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 1,
    "D_FAM_NB": 1,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES022",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 1,
    "D_FAM_NB": 1,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES023",
    "PERIODE": 1,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 3.0,
    "NB_HOSPIT": 3.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 1,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES023",
    "PERIODE": 2,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 0.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 1,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES024",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "15+ ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 4.0,
    "NB_HOSPIT": 3.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 1,
    "D_FAM_NB": 1,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES024",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "15+ ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 1,
    "D_FAM_NB": 1,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES025",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 1.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 1,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES025",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 1,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES026",
    "PERIODE": 1,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": NaN,
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 2.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES026",
    "PERIODE": 2,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": NaN,
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES027",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 1.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 1,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES027",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 1,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES028",
    "PERIODE": 1,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 1.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES028",
    "PERIODE": 2,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES029",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 2.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES029",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES030",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 2.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES030",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES031",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 1.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES031",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES032",
    "PERIODE": 1,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 1.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES032",
    "PERIODE": 2,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES033",
    "PERIODE": 1,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": NaN,
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 0.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES033",
    "PERIODE": 2,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": NaN,
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES034",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 1.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES034",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES035",
    "PERIODE": 1,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "10–14 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 4.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES035",
    "PERIODE": 2,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "10–14 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES036",
    "PERIODE": 1,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": NaN,
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 1.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES036",
    "PERIODE": 2,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": NaN,
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES037",
    "PERIODE": 1,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 1.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES037",
    "PERIODE": 2,
    "SEXE_lbl": "Masculin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES038",
    "PERIODE": 1,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 0.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 1,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES038",
    "PERIODE": 2,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 1,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES039",
    "PERIODE": 1,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 1.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 1,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES039",
    "PERIODE": 2,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 0.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 1,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES040",
    "PERIODE": 1,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 2.0,
    "NB_HOSPIT": 0.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 1,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES040",
    "PERIODE": 2,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "0–4 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 0,
    "D_PARENT_SEUL": 1,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 0,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES041",
    "PERIODE": 1,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": NaN,
    "NB_CVO": 1.0,
    "NB_HOSPIT": 1.0,
    "NB_TRANSFUS": 0.0,
    "VACC_PEV": NaN,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": NaN,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 1,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  },
  {
    "patient_id": "CES041",
    "PERIODE": 2,
    "SEXE_lbl": "Féminin",
    "TYPE_lbl": "SS",
    "AGE_GROUPE": "5–9 ans",
    "DOSSIER_COMPLET": 1,
    "RDV_HONORE": 1.0,
    "NB_CVO": NaN,
    "NB_HOSPIT": NaN,
    "NB_TRANSFUS": NaN,
    "VACC_PEV": 1.0,
    "VACC_ANT_PEV": 1.0,
    "AF_PRISE": 1.0,
    "AF_PRISE_ANT": 1,
    "D_PAUVRETE": 0,
    "D_DISTANCE": 1,
    "D_PARENT_SEUL": 0,
    "D_SEPARES": 0,
    "D_SOUTIEN": 0,
    "D_FAM_NB": 1,
    "D_CROYANCES": 0,
    "D_MED_TRAD": 0
  }
];
